name: cron
description: A time-based job scheduler similar to cron. Run tasks periodically at fixed times or intervals.
version: 0.2.3
homepage: https://github.com/agilord/cron

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
